hellod_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("poll.urls")),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

movies/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index')
]

poll/urls.py
from django.urls import path
from . import views

app_name= "poll"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name='detail'),
    path("<int:question_id>/results/", views.results, name='results'),
    path("<int:question_id>/vote/", views.vote, name='vote')
]

movies/models.py
from django.db import models
from django.utils import timezone

class Genre(models.Model):
    name = models.CharField(max_length=255)
    
class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

poll/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date piblished")

    def __str__(self) -> str:
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.choice_text

hellod_app/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    return HttpResponse('Tsá world!')

poll/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.db.models import F
from django.urls import reverse

from .models import Choice, Question


def index(request):
    latest_questions_list = Question.objects.order_by("-pub_date")[:5]
    # template = loader.get_template("poll/index.html")
    context = {
        "latest_question_list": latest_questions_list
    }
    return render(request, "poll/index.html", context)

def detail(request, question_id):
    try:
        # question = Question.objects.get(pk=question_id)
        question = get_object_or_404(Question, pk=question_id)
    except Question.DoesNotExist:
        raise Http404('Question does not exist.')
    return render(request, "poll/detail.html", {"question": question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "poll/results.html", {"question": question})

def vote(request, question_id):
    # return HttpResponse("You are voting in question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "poll/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice."
            }
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("poll:results", args=(question_id,)))

poll/templates/poll/detail.html
{% comment %} <h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> {% endcomment %}

<form action="{% url 'poll:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

poll/templates/poll/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are availabe.</p>
{% endif %}

poll/templates/poll/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll:detail' question.id %}">Vote again?</a>